# Generated by Django 5.2.17 on 2026-09-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
